# To work, you need to have docker-compose up in allinbits/eclesia-indexer
# and create there a database `metadata-govgen-dapp`
# CREATE DATABASE "metadata-govgen-dapp";
networks:
  eclesia-indexer_default:
    external: true

services:
  hasura:
    image: hasura/graphql-engine:v2.38.0.cli-migrations-v3
    ports:
      - "8081:8080"
    restart: always
    networks:
      - eclesia-indexer_default
    environment:
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: "true"
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/metadata-govgen-dapp
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_METADATA_DIR: "/hasura-metadata"
    volumes:
      - ./hasura/metadata:/hasura-metadata
